baseURL = "https://manandearth.github.io/"
languageCode = "en-us"
title = "Man and Earth"
theme="archie"
publishDir = ".."
ignoreErrors = ["error-remote-getjson"]

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Man meddling with the [environment](https://wikipedia.com/wiki/environment)"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/manandearth"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/GefenAdam/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/manandearth/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4